# Generated by Django 6.1.1 on 2026-09-07 15:27

import django.db.models.deletion
from django.db import migrations, models


def migrate_old_data(apps, schema_editor):
    Trip = apps.get_model('planner', 'Trip')
    Destination = apps.get_model('planner', 'Destination')
    Place = apps.get_model('planner', 'Place')

    for trip in Trip.objects.all():
        destination = Destination.objects.create(
            trip=trip,
            country=trip.country,
            city=trip.city
        )

        Place.objects.filter(trip=trip).update(
            destination=destination
        )


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                (
                    'country',
                    models.CharField(max_length=100)
                ),
                (
                    'city',
                    models.CharField(max_length=100)
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True)
                ),
                (
                    'trip',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='destinations',
                        to='planner.trip'
                    )
                ),
            ],
        ),

        migrations.AddField(
            model_name='place',
            name='destination',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='places',
                to='planner.destination'
            ),
        ),

        migrations.RunPython(
            migrate_old_data,
            migrations.RunPython.noop
        ),

        migrations.RemoveField(
            model_name='place',
            name='trip',
        ),

        migrations.RemoveField(
            model_name='trip',
            name='city',
        ),

        migrations.RemoveField(
            model_name='trip',
            name='country',
        ),
    ]